paths:
    cuda_path: "/usr/local/cuda/lib64"
data:
    data_path: "D:/ProjectImages/SyntheticContrast"
    target: ["AC", "VC"]
    source: ["HQ"]
    segs: ["AC"]
    times: "times_ordinal.json"
    down_sample: 1
    patch_size: [64, 64, 64]
    norm_type: "minmax"
    norm_param_1: -500
    norm_param_2: 2500
    data_type: "unpaired"
    num_examples: 4
    cv_folds: 6
    fold: 5
expt:
    mb_size: 1
    save_every: 10
    model: "UNet" # "GAN" or "HyperGAN"
    epochs: 1000
    verbose: true # Output model summary
    graph: false # Save graph for visualisation in Tensorboard
    log_scalars: true # Log losses for visualisation in Tensorboard
    log_histograms: false # Log weights for visualisation in Tensorboard
    save_model: true
    focal: true # Use focal loss or not
hyperparameters:
    img_dims: [64, 64, 64]
    opt: [1.0e-4, 0.9, 0.999]
    mu: 0.1 # Focal loss weighting (0.0 == OFF)
    ngf: 32 # Starting channels
    g_layers: 5
    g_time_layers: ["up_0", "up_1", "up_2", "up_3"]
augmentation:
    type: "differentiable" # "standard", "differentiable" or null
    depth: 64
    flip_prob: 0.5 # Settings for standard augmentation
    rotation: 45.0
    scale: [0.8, 1.6]
    shear: 15.0
    translate: [0.25, 0.25]
    colour: true # Settings for differentiable augmentation
    translation: true
    cutout: true
